NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/ca.crt
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/ca.crt
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/ca.crt
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/ca.crt
        OrganizationalUnitIdentifier: orderer
